brisvag/blik

ntp/tomo_viewer.py
Testing the workflow. Introduces a working `StarViewer` class.
=> broken, but functioning starviewer

peepingtom/visualisation/__init__.py, tests/analysis/test_particles.py, tests/core/datablocks/test_base.py, tests/core/datablocks/test_orientationblock.py, tests/core/datablocks/test_pointblock.py, tests/test_data/blocks.py, tests/utils/helpers/test_dataframe_helper.py, tests/utils/validators/test_pandas.py, tests/visualisation/test_depictors/test_images.py, tests/visualisation/test_depictors/test_lines.py, tests/visualisation/test_depictors/test_particles.py, tests/visualisation/test_depictors/test_points.py
I also fixed some old ones. This will probably break a bit when we merge with the other active PRs, cause some small refactoring happened in between.
=> A bunch of new tests

peepingtom/core/alchemists/from_points.py, peepingtom/core/datablocks/meshblock.py, peepingtom/core/datablocks/transformblock.py, peepingtom/core/models/base.py, tests/core/datablocks/test_meshblock.py
There were a few silly import errors and name errors causing failing tests, all fixed!
=> repair import errors causing failing tests

peepingtom/__init__.py, peepingtom/entry_points/peep.py, requirements.txt, setup.cfg, setup.py
files can now be `peep`ed at directly from the command line!
=> Add a basic CLI for the peep function

peepingtom/io_/read/read.py
simple PR to add support for .map files which are just .mrc files
=> add reading of .map files

peepingtom/analysis/_tests/test_particles.py, peepingtom/analysis/particles.py, peepingtom/core/datablocks/particleblock.py, peepingtom/core/datablocks/propertyblock.py
Simple change that makes `PropertyBlock` more specific (now a dataframe) and introduces a metadata dict for `ParticleBlock`s.
=> Particle properties

peepingtom/io_/reading/star.py
=> Fix relion shifts

peepingtom/_tests/test_peeper.py, peepingtom/datablocks/abstractblocks/datablock.py, peepingtom/datablocks/abstractblocks/metamultiblock.py, peepingtom/datablocks/abstractblocks/multiblock.py, peepingtom/peeper.py
This allows for tracking of a datablock's parent through slicing. It's also clearer what's what.
=> Separated concepts of parent and view

peepingtom/_tests/test_peeper.py, peepingtom/depictors/napari/_tests/test_lines.py, peepingtom/depictors/napari/_tests/test_particles.py, peepingtom/gui/_tests/test_napari.py, peepingtom/gui/viewer.py, peepingtom/utils/_tests/test_dispatch_list.py, peepingtom/utils/dispatchlist.py
Added a few tests (and fixed some bugs that emerged in the process :P).
=> More tests

peepingtom/datablocks/simpleblocks/propertyblock.py, peepingtom/io_/reading/star.py, peepingtom/io_/reading/tbl.py
Closes #66, while adding ability to set properties without having to access the `data` of a propertyblock.
=> protect properties from changes

.github/workflows/make_docs.yml, .github/workflows/publish_pypi.yml, .github/workflows/test_pr.yml
Some stuff was leftover in the github workflows.
=> update name in workflows

README.md
Hi @alisterburt and @brisvag ,
congrats to the release of this super cool plugin! This minor change will make the logo show on the napari hub page.
Cheers,
Robert
=> correct link to image

blik/napari.yaml, setup.cfg
`cryohub` 0.4.0 added a simple hdf reader. Exposing it here is very simple :)
=> Add hdf reader

.pre-commit-config.yaml, blik/_tests/test_reader.py, blik/reader.py, blik/utils.py, blik/widgets/main_widget.py, setup.cfg
Surface picking tool based on on https://github.com/morphometrics/morphosamplers/pull/7.
=> Surface picking

blik/_tests/test_reader.py, blik/reader.py, blik/widgets/main_widget.py, blik/writer.py, setup.cfg
Use new poseset model from cryotypes 0.2.0. This also helped find and fix several bugs here and there in cryohub and here.
=> Use new poseset model

README.md
Add some details on the widget to the readme.
=> Some readme changes

src/blik/reader.py, src/blik/widgets/main_widget.py
Ensure `feature_defaults` behave properly with orientations, and that IO accounts for edge cases (especially relevant when manual picking)
=> Fix orientations defaults and related IO

.github/workflows/ci.yml
See https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-first-deployment-with-github_token
=> Fix failing docs deploy

pyproject.toml, src/blik/widgets/picking.py
=> Fix interpolation and spline issues

.github/workflows/ci.yml, pyproject.toml, src/blik/napari.yaml
Bump to napari 0.5 and use new contributable menus.
=> use contributable menus from napari 0.5.0

src/blik/reader.py, src/blik/widgets/main_widget.py
Add units and axis labels to the layer data, and enable labels on the viewer.
=> Add units and axis labels

src/blik/napari.yaml, src/blik/remote_data.py
Sample data using https://zenodo.org/records/6504890.
cc @alisterburt
=> add sample data using HIV dataset

src/blik/napari.yaml, src/blik/widgets/picking.py
Not much, but helps in a pinch.
=> Add simple widget for rotating particles
